version: "3.6"

services:
  http:
    container_name: projet_http
    build: apache/
    ports:
      - "10000:80"
    volumes:
      - ../app:/app
      - ./bash/.bashrc:/root/.bashrc
    environment:
      - ALLOW_OVERRIDE=true
      - SECRET=AAAAAAAAAAAA
    networks:
      - frontend
      - backend
    env_file:
      - ./mysql/sf_mysql.env
      - ./apache/sf_mail.env
      - ./php/sf.env
    links:
      - php:php
      - db:db
      - maildev:maildev

  php:
    container_name: projet_php
    build: php/
    tty: true
    volumes:
      - ../app:/app
    networks:
      - backend

  db:
    container_name: projet_db
    image: mysql:5.5
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projet
      - MYSQL_USER=user
      - MYSQL_PASSWORD=UnTrucDrole
    ports:
      - "10001:3306"
    networks:
      - backend

  maildev:
    container_name: projet_mail
    image: djfarrelly/maildev
    ports:
      - "10002:80"

networks:
  frontend:
  backend: