version: "3.6"

services:
  http:
    container_name: project_name_http
    build: .
    ports:
      - "10000:80"
    volumes:
      - ../app:/var/www/html
      - .bashrc:/root/.bashrc
    environment:
      - ALLOW_OVERRIDE=true
      - SECRET=AAAAAAAAAAAA
    networks:
      - frontend
      - backend
    env_file:
      - sf_mysql.env
      - sf_mail.env
      - sf.env
    links:
      - db:db
      - maildev:maildev

  db:
    container_name: project_name_db
    image: mysql:5.7
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=project_name
      - MYSQL_USER=user
      - MYSQL_PASSWORD=UnTrucDrole
    ports:
      - "10001:3306"
    networks:
      - backend

  maildev:
    container_name: project_name_mail
    image: djfarrelly/maildev
    ports:
      - "10002:80"

networks:
  frontend:
  backend: