version: "3.6"

services:
  http:
    container_name: api_http
    image: httpd:2.4
    ports:
      - "10000:80"
    volumes:
      - ../src:/usr/local/apache2/htdocs
      - ./bash/.bashrc:/root/.bashrc
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/local.dev.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    environment:
      - ALLOW_OVERRIDE=true
      - SECRET=AAAAAAAAAAAA
    env_file:
      - ./mysql/sf_mysql.env
      - ./apache/sf_mail.env
      - ./php/sf.env
    links:
      - php:php
      - db:db
      - maildev:maildev

  php:
    container_name: api_php
    image: php:7.2-fpm
    tty: true

  db:
    container_name: api_db
    image: mysql:5.5
    volumes:
      - ./volume/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=projet
      - MYSQL_USER=user
      - MYSQL_PASSWORD=UnTrucDrole
    ports:
      - "10001:3306"

  maildev:
    container_name: api_mail
    image: djfarrelly/maildev
    ports:
      - "10002:80"